language: ruby
branches:
  only:
    - master
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database highfive_test;' -U postgres
cache:
  bundler: true
  directories:
    - /home/travis/.rvm/
