language: ruby
branches:
  only:
    - master
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database highfive_test;' -U postgres
  - gem install bundler -v 1.17.1
env:
  SLACK_VERIFICATION_TOKEN: abc
cache:
  bundler: true
  directories:
    - /home/travis/.rvm/
